/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libJNICalculadora_CalculadoraCostosPresupuesto */

#ifndef _Included_libJNICalculadora_CalculadoraCostosPresupuesto
#define _Included_libJNICalculadora_CalculadoraCostosPresupuesto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libJNICalculadora_CalculadoraCostosPresupuesto
 * Method:    precioVentaAbsor
 * Signature: (DDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_libJNICalculadora_CalculadoraCostosPresupuesto_precioVentaAbsor
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     libJNICalculadora_CalculadoraCostosPresupuesto
 * Method:    precioVentaDir
 * Signature: (DDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_libJNICalculadora_CalculadoraCostosPresupuesto_precioVentaDir
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
